// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ShowText","status":true,"description":"Показывает текст чуть выше середины экрана, который исчезает через определенное время, с подчеркиванием текста.","parameters":{}},
{"name":"WD_Quest","status":true,"description":"Custom Quest Plugin for RPG Maker MZ","parameters":{"linebreak1":"================","Title":"Журнал","fontsize":"40","dynamicDescSize":"false","paddingValue":"50","descriptionSize":"20","infoalign":"center","listSize":"20","listAlign":"center","linebreak2":"================","giverprefix":"От:","areaprefix":"Локация:","statusname":"Статус:","questcompleted":"Завершено","questongoing":"В процессе","questfailed":"Провалено","linebreak3":"================","menucommand":"true","commandname":"Журнал","linebreak4":"================","titleFlag":"true","layoutAlign":"layout1","layoutSize":"size1","touchCancel":"true","skinSettings":"{\"skinFlag\":\"false\",\"skinName\":\"\",\"redT\":\"0\",\"greenT\":\"0\",\"blueT\":\"0\"}"}}
];
