// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ShowText","status":true,"description":"Показывает текст чуть выше середины экрана, который исчезает через определенное время, с подчеркиванием текста.","parameters":{}},
{"name":"WD_Quest","status":true,"description":"Custom Quest Plugin for RPG Maker MZ","parameters":{"linebreak1":"================","Title":"Журнал","fontsize":"40","dynamicDescSize":"true","paddingValue":"50","descriptionSize":"20","infoalign":"center","listSize":"20","listAlign":"left","linebreak2":"================","giverprefix":"От:","areaprefix":"Локация:","statusname":"Статус:","questcompleted":"Завершено","questongoing":"В процессе","questfailed":"Провалено","linebreak3":"================","menucommand":"true","commandname":"Журнал","linebreak4":"================","titleFlag":"true","layoutAlign":"layout1","layoutSize":"size1","touchCancel":"true","skinSettings":"{\"skinFlag\":\"false\",\"skinName\":\"\",\"redT\":\"0\",\"greenT\":\"0\",\"blueT\":\"0\"}"}},
{"name":"ShowTime","status":true,"description":"Используйте метод плагина ShowTime в параллельном событии для отображения времени.","parameters":{"x":"20","y":"20"}},
{"name":"YEP_RegionRestrictions","status":true,"description":"v1.00 Use regions to block out Events and/or the player from\nbeing able to venture into those spots.","parameters":{"Player Restrict":"0","Event Restrict":"2","All Restrict":"1","Player Allow":"0","Event Allow":"3","All Allow":"0"}},
{"name":"OrangeOverlay","status":true,"description":"v1.1.4 - Adds overlay images to the map <OrangeOverlay>","parameters":{"Organized Folders":"false","Parallax Layer Filename":"par","Ground Layer Filename":"ground","Light Layer Filename":"light","Shadow Layer Filename":"shadow","Light Opacity":"185","Quick Start":"true","Bush Region ID":"7","Fog Switch ID":"98","Light Switch ID":"97","Parallax Switch ID":"96","Shadow Switch ID":"95"}},
{"name":"Tsukitsune_animatedOverlayAddon","status":true,"description":"| Animated Overlay Addon : Version - 1.0.4 | This plugin adds to the OrangeOverlay plugin, and allows you to animate parallaxes.","parameters":{}},
{"name":"PathFinding","status":true,"description":"v1.0.1 - Pathfinding, move route generator.","parameters":{}}
];
